### ISSUE TITLE
Forever loading

### ISSUE THREAD

**Issue by tholene** [banjo/qties-devtools#3]
I opened the Qtie devtools 30 minutes ago and it's still not done loading!!! 

10 seconds after opening
<img width="1337" alt="Unify" src="https://github.com/banjo/qties-devtools/assets/3428881/6c870faf-62e4-40c1-82e3-8e7266a31355">

30 minutes after opening
<img width="1337" alt="Unify" src="https://github.com/banjo/qties-devtools/assets/3428881/d260ad21-65ea-48b6-9c82-7bbaceecb36d">

**Comment by banjo** [comment]
Fixed in commit 0753efc.
